### ISSUE TITLE
websocket doesn't work with feed from queue?

### ISSUE THREAD

**Issue by lu0x1a0** [thedirtyfew/dash-extensions#40] opened 2021-01-09 02:16 UTC
I'm trying to use data from a queue as a live data feed into the websocket. and for some reason even though it dequeues, it doesn't updates the graph. 
```
import json
import dash_html_components as html
import random
import dash_core_components as dcc
import plotly.graph_objects as go
from gevent import sleep
from dash import Dash
from dash.dependencies import Input, Output, State
from dash_extensions import WebSocket
from dash_extensions.websockets import SocketPool, run_server

import threading, queue

def genData(q):
    while True:
        sleep(random.uniform(0, 2))  # delay between data events
        q.put(random.uniform(0, 1))  # the data value

# This block runs asynchronously.
def ws_handler(ws,q):
    # for data in data_feed():
    #     ws.send(json.dumps(data))  # send data
    while len(list(q.queue))!=0:
        data = q.get()
        ws.send(json.dumps(data))
        q.task_done() 
q = queue.Queue()

# Create example app.
app = Dash(prevent_initial_callbacks=True)
socket_pool = SocketPool(app, handler=lambda x: ws_handler(x,q))
app.layout = html.Div([
    dcc.Graph(id="graph", figure=go.Figure(go.Scatter(x=[], y=[]))), 
    WebSocket(id="ws")
])


@app.callback(Output("graph", "figure"), [Input("ws", "message")], [State("graph", "figure")])
def update_graph(msg, figure):
    x, y = figure['data'][0]['x'], figure['data'][0]['y']
    return go.Figure(data=go.Scatter(x=x + [len(x)], y=y + [float(msg['data'])]))


if __name__ == '__main__':
    threading.Thread(target = genData,daemon =True, args = (q,) ).start()
    run_server(app, port=5000)  # 5000 if the default port
```

**Comment by emilhe** [comment] 2021-01-09 18:21
You have mixing the sleep function from `gevent` (serving the websockets) and `threading`. Hence if you move the line "sleep(random.uniform(0, 2))  # delay between data events" into the ws handler, it should work.

```
import json
import dash_html_components as html
import random
import dash_core_components as dcc
import plotly.graph_objects as go
from gevent import sleep
from dash import Dash
from dash.dependencies import Input, Output, State
from dash_extensions import WebSocket
from dash_extensions.websockets import SocketPool, run_server

import threading, queue


def genData(q):
    while True:
        q.put(random.uniform(0, 1))  # the data value


# This block runs asynchronously.
def ws_handler(ws, q):
    # for data in data_feed():
    #     ws.send(json.dumps(data))  # send data
    while len(list(q.queue)) != 0:
        data = q.get()
        sleep(random.uniform(0, 2))  # delay between data events
        ws.send(json.dumps(data))
        q.task_done()


q = queue.Queue()

# Create example app.
app = Dash(prevent_initial_callbacks=True)
socket_pool = SocketPool(app, handler=lambda x: ws_handler(x, q))
app.layout = html.Div([
    dcc.Graph(id="graph", figure=go.Figure(go.Scatter(x=[], y=[]))),
    WebSocket(id="ws")
])


@app.callback(Output("graph", "figure"), [Input("ws", "message")], [State("graph", "figure")])
def update_graph(msg, figure):
    x, y = figure['data'][0]['x'], figure['data'][0]['y']
    return go.Figure(data=go.Scatter(x=x + [len(x)], y=y + [float(msg['data'])]))


if __name__ == '__main__':
    threading.Thread(target=genData, daemon=True, args=(q,)).start()
    run_server(app, port=5000)  # 5000 if the default port

```

**Comment by lu0x1a0** [comment] 2021-01-10 01:47
Hi again, the above code does work,  but is somewhat against my goal as I am trying empty the queue immediately, and circumstantially, I haven't found anyway to pipe multiple same function calls at uneven intervals to a generator, so I'm stuck with the queue. I tried having time.sleep(random.uniform(1,2)) in genData and it doesn't call update_graph without having an extra sleep in ws_handler. Any idea of how to solve such a problem? 

Many thanks.

**Comment by lu0x1a0** [comment] 2021-01-10 02:02
That works, thank you very much. but out of curiousity, I also tried with time.sleep inside the genData function without sleep in ws_handler, and it also doesn't call the update_graph function. Why wouldn't that work?

**Comment by emilhe** [comment] 2021-03-20 18:20
I am not sure. But as the issue is resolve, I will close it for now :)

**Closed by emilhe** 2021-03-20 18:20 UTC
